platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.3

inputs:
- name: flight-school

run:
  path: ./flight-school/ci/test.sh


resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/pellegrino/flight-school
    branch: master

jobs:
- name: test-app
  plan:
  - get: flight-school
  - task: tests
    file: flight-school/build.yml
